# @package _global_

rewards:
  _config:
    reward_prefix: "ref_"

  is_alive:
    weight: 0.5
    params: {}

  root_pos_xy_tracking_exp:
    weight: 0.0
    params:
      std: 0.2
      ref_prefix: ${rewards._config.reward_prefix}

  root_rot_tracking_exp:
    weight: 0.0
    params:
      std: 0.4
      ref_prefix: ${rewards._config.reward_prefix}

  root_rel_keybodylink_pos_tracking_l2_exp:
    weight: 1.0
    params:
      keybody_names: ${robot.key_bodies}
      std: 0.3
      ref_prefix: ${rewards._config.reward_prefix}

  root_rel_keybodylink_rot_tracking_l2_exp:
    weight: 1.0
    params:
      keybody_names: ${robot.key_bodies}
      std: 0.4
      ref_prefix: ${rewards._config.reward_prefix}

  root_lin_vel_tracking_rel_ratio_exp:
    weight: 2.0
    params:
      std: 1.0
      eps: 0.1
      ref_prefix: ${rewards._config.reward_prefix}

  root_ang_vel_tracking_rel_ratio_exp:
    weight: 2.0
    params:
      std: 1.0
      eps: 0.1
      ref_prefix: ${rewards._config.reward_prefix}

  local_reward_point_body_pos_tracking_exp:
    weight: 5.0
    params:
      std: 0.1
      ref_prefix: ${rewards._config.reward_prefix}
      reward_point_body:
        - torso_link
        - left_wrist_yaw_link
        - right_wrist_yaw_link
        - left_ankle_roll_link
        - right_ankle_roll_link
      reward_point_body_offset:
        - [0.0, 0.0, 0.5]
        - [0.0, 0.0, 0.0]
        - [0.0, 0.0, 0.0]
        - [0.0, 0.0, 0.0]
        - [0.0, 0.0, 0.0]
      point_weights:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0

  global_keybodylink_lin_vel_tracking_l2_exp:
    weight: 1.0
    params:
      keybody_names: ${robot.key_bodies}
      std: 1.0
      ref_prefix: ${rewards._config.reward_prefix}

  global_keybodylink_ang_vel_tracking_l2_exp:
    weight: 1.0
    params:
      keybody_names: ${robot.key_bodies}
      std: 3.14
      ref_prefix: ${rewards._config.reward_prefix}

  action_rate_l2:
    weight: -0.1
    params: {}

  # joint_acc_l2:
  #   weight: -1.0e-6
  #   params: {}

  joint_pos_limits:
    weight: -10.0
    params:
      asset_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: robot
        joint_names:
          - ".*"

  undesired_contacts:
    weight: -0.1
    params:
      threshold: 1.0
      sensor_cfg:
        _target_: isaaclab.managers.scene_entity_cfg.SceneEntityCfg
        name: contact_forces
        body_names:
          - ${robot.undesired_contacts_regrex}
